version: "3.9"

services:
  telegram_rss:
    build: .
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./media:/app/media
      - ./session_name.session:/app/session_name.session
      - ./config.json:/app/config.json
